import { editorLocalization } from "../editorLocalization";

export var turkishStrings = {
  //survey templates
  survey: {
    edit: "Düzenle",
    dropQuestion: "Lütfen soldaki Araç Kutusundan buraya bir soru bırakın.",
    copy: "Kopyala",
    addToToolbox: "Araç kutusuna ekle",
    deletePanel: "Paneli sil",
    deleteQuestion: "Soruyu sil",
    convertTo: "Dönüştür",
    drag: "Öğeyi sürükleyin"
  },
  //questionTypes
  qt: {
    default: "Varsayılan",
    checkbox: "Çoklu Seçenek",
    comment: "Yorum",
    imagepicker: "Görüntü seçici",
    dropdown: "Açılır menü",
    file: "Dosya",
    html: "Html",
    matrix: "Matrix (tek seçenek)",
    matrixdropdown: "Matrix (çoktan seçmeli)",
    matrixdynamic: "Matrix (dinamik satırlar)",
    multipletext: "Çoklu Metin",
    panel: "Panel",
    paneldynamic: "Panel (dinamik paneller)",
    radiogroup: "Tek Seçenek",
    rating: "Puanlama",
    text: "Metin",
    boolean: "Boolean",
    expression: "İfade"
  },
  //Strings in Editor
  ed: {
    defaultLocale: "Varsayılan ({0})",
    survey: "Anket",
    settings: "Anket Ayarları",
    editSurvey: "Anketi Düzenle",
    addNewPage: "Yeni Sayfa Ekle",
    moveRight: "Sağa Kaydır",
    moveLeft: "Sola Kaydır",
    deletePage: "Sayfa Sil",
    editPage: "Sayfa Düzenle",
    edit: "Düzenle",
    newPageName: "sayfa",
    newQuestionName: "soru",
    newPanelName: "panel",
    testSurvey: "Test Anketi",
    testSurveyAgain: "Yeniden Test Anketi",
    testSurveyWidth: "Anket genişliği: ",
    embedSurvey: "Anket Gömme",
    translation: "Çeviri",
    saveSurvey: "Anketi Kaydet",
    designer: "Anket Tasarımcısı",
    jsonEditor: "JSON Editör",
    undo: "Geri Alma",
    redo: "Yeniden Yapma",
    options: "Seçenekler",
    generateValidJSON: "Geçerli JSON Oluştur",
    generateReadableJSON: "Okunabilir JSON Üret",
    toolbox: "Araç Kutusu",
    toolboxGeneralCategory: "General",
    delSelObject: "Seçilen nesneyi sil",
    editSelObject: "Seçilen nesneyi düzenle",
    correctJSON: "Lütfen JSON’u düzeltin.",
    surveyResults: "Anket Sonucu: ",
    surveyResultsTable: "Tablo Olarak",
    surveyResultsJson: "JSON Olarak",
    resultsTitle: "Soru Başlığı",
    resultsName: "Soru Adı",
    resultsValue: "Cevap Değeri",
    resultsDisplayValue: "Varsayılan Değer",
    modified: "Değiştirilmiş",
    saving: "Kaydediliyor",
    saved: "Kaydedildi",
    saveError: "Hata! Editör içeriği kaydedilmedi.",
    translationAddLanguage: "Tercüme edilecek dili seçin",
    translationShowAllStrings: "Bütün içeriği göster",
    translationShowAllPages: "Bütün sayfaları göster",
    translationNoStrings: "Çevirelecek içerik yok. Lütfen filtreyi değiştirin.",
    translationExportToSCVButton: "CSV'ye aktar",
    translationImportFromSCVButton: "CSV'den içe aktar",
    translationMergeLocaleWithDefault: "Merge {0} with default locale"
  },
  //Property names in table headers
  pel: {
    isRequired: "Gerekli alan?"
  },
  //Property Editors
  pe: {
    apply: "Uygulamak",
    ok: "Tamam",
    cancel: "İptal",
    reset: "Sıfırla",
    close: "Kapat",
    delete: "Sil",
    addNew: "Yeni Ekle",
    addItem: "Bir öğe eklemek için tıklayın...",
    removeAll: "Tümünü Sil",
    edit: "Düzenle",
    itemValueEdit: "Görünürse",
    editChoices: "Seçimi Düzenle",
    move: "Taşı",
    empty: "<empty>",
    notEmpty: "<edit value>",
    fastEntry: "Hızlı Giriş",
    formEntry: "Form Girişi",
    testService: "Servisi Test Et",
    conditionSelectQuestion: "Soru seç...",
    conditionValueQuestionTitle: "Lütfen değeri girin / seçin",
    conditionButtonAdd: "Ekle",
    conditionButtonReplace: "Değiştir",
    conditionHelp:
      "Please enter a boolean expression. It should return true to keep the question/page visible. For example: {question1} = 'value1' or ({question2} * {question4}  > 20 and {question3} < 5)",
    expressionHelp:
      "Please enter an expression. You may use curly brackets to get access to the question values: '{question1} + {question2}', '({price}*{quantity}) * (100 - {discount})'",
    aceEditorHelp: "İfade tamamlama ipucu almak için ctrl + boşluk tuşlarına basın",
    aceEditorRowTitle: "Geçerli satır",
    aceEditorPanelTitle: "Geçerli panel",
    showMore: "Daha fazla ayrıntı için lütfen belgeleri inceleyin",
    conditionShowMoreUrl:
      "https://surveyjs.io/Documentation/LibraryParameter?id=Question&parameter=visibleIf",
    assistantTitle: "Mevcut sorular:",
    cellsEmptyRowsColumns: "En az bir sütun veya satır olmalı",

    propertyIsEmpty: "Lütfen bir değer girin",
    value: "Değer",
    text: "Metin",
    rowid: "Satır ID",
    imageLink: "Resim Bağlantısı",
    columnEdit: "Sütunu Düzenle: {0}",
    itemEdit: "Ögeyi Düzenle: {0}",

    url: "URL",
    path: "Path",
    valueName: "Value name",
    titleName: "Title name",

    hasOther: "Has other item",
    otherText: "Other item text",
    name: "Name",
    title: "Title",
    cellType: "Cell type",
    colCount: "Column count",
    choicesOrder: "Select choices order",
    visible: "Is visible?",
    isRequired: "Is required?",
    startWithNewLine: "Is start with new line?",
    rows: "Row count",
    placeHolder: "Input place holder",
    showPreview: "Is image preview shown?",
    storeDataAsText: "Store file content in JSON result as text",
    maxSize: "Maximum file size in bytes",
    imageHeight: "Image height",
    imageWidth: "Image width",
    rowCount: "Row count",
    columnLayout: "Columns layout",
    addRowLocation: "Add row button location",
    addRowText: "Add row button text",
    removeRowText: "Remove row button text",
    minRateDescription: "Minimum rate description",
    maxRateDescription: "Maximum rate description",
    inputType: "Input type",
    optionsCaption: "Options caption",
    defaultValue: "Default value",
    cellsDefaultRow: "Default cells texts",

    surveyEditorTitle: "Anket ayarlarını düzenle",
    qEditorTitle: "Düzenle: {0}",

    maxLength: "Maksimum uzunluk",

    //survey
    showTitle: "Başlığı Göster / Gizle",
    locale: "Varsayılan Dil",
    mode: "Mod (düzenleme/salt okunur)",
    clearInvisibleValues: "Görünmez değerleri temizle",
    cookieName: "Cookie adı (yerel olarak anket çalışmasını iki kez devre dışı bırakmak için)",
    sendResultOnPageNext: "Sonraki sayfada anket sonuçlarını gönderin",
    storeOthersAsComment: "'Diğerleri' değerini ayrı bir alanda saklayın",
    showPageTitles: "Sayfa başlıklarını görüntüle",
    showPageNumbers: "Sayfa numaralarını görüntüle",
    pagePrevText: "Önceki sayfa düğmesi metni",
    pageNextText: "Sonraki sayfa düğmesi metni",
    completeText: "Tamamlama düğmesi metni",
    startSurveyText: "Başla düğmesi metni",
    showNavigationButtons: "Gezinme düğmelerini göster (varsayılan gezinme)",
    showPrevButton: "Önceki düğmesini göster (kullanıcı önceki sayfaya dönebilir)",
    firstPageIsStarted: "Anketteki ilk sayfa bir başlangıç sayfasıdır.",
    showCompletedPage: "Tamamlanan sayfayı sonunda göster (completedHtml)",
    goNextPageAutomatic:
      "Tüm soruları cevaplarken, otomatik olarak bir sonraki sayfaya geçin",
    showProgressBar: "İlerleme çubuğunu göster",
    questionTitleLocation: "Soru başlığı konumu",
    requiredText: "Soru zorunlu sembolü(s)",
    questionStartIndex: "Soru başlangıç dizini (1, 2 or 'A', 'a')",
    showQuestionNumbers: "Soru numaralarını göster",
    questionTitleTemplate:
      "Soru başlığı şablonu, varsayılan: '{no}. {zorunlu} {başlık}'",
    questionErrorLocation: "Soru hata yeri",
    focusFirstQuestionAutomatic: "Sayfayı değiştirmek için ilk soruya odaklanın",
    questionsOrder: "Elements order on the page",
    maxTimeToFinish: "Anketi bitirmek için maksimum süre",
    maxTimeToFinishPage: "Ankette bir sayfayı bitirmek için maksimum süre",
    showTimerPanel: "Zamanlayıcı panelini göster",
    showTimerPanelMode: "Zamanlayıcı paneli modunu göster",
    renderMode: "Render modu",
    allowAddPanel: "Panel eklenmesine izin ver",
    allowRemovePanel: "Panelin çıkarılmasına izin ver",
    panelAddText: "Panel metni ekleme",
    panelRemoveText: "Panel metni silme",
    isSinglePage: "Tüm öğeleri tek sayfada göster",

    tabs: {
      general: "Genel",
      fileOptions: "Seçenekler",
      html: "Html Düzenleyici",
      columns: "Sütunlar",
      rows: "Satırlar",
      choices: "Seçimler",
      items: "Ögeler",
      visibleIf: "Görünüyorsa",
      enableIf: "Etkinse",
      rateValues: "Oylama Değerleri",
      choicesByUrl: "Web'den seçmeler",
      matrixChoices: "Varsayılan Seçim",
      multipleTextItems: "Metin Girişleri",
      validators: "Doğrulayıcılar",
      navigation: "Navigation",
      question: "Soru",
      completedHtml: "Html Tamamlanmış",
      loadingHtml: "Html Yükleniyor",
      timer: "Zamanlayıcı/Quiz",
      triggers: "Tetikleyiciler",
      templateTitle: "Şablon başlığı"
    },
    editProperty: "Özelliği düzenle '{0}'",
    items: "[ Ögeler: {0} ]",

    enterNewValue: "Lütfen, değeri giriniz.",
    noquestions: "Ankette herhangi bir soru yok.",
    createtrigger: "Lütfen tetikleyici oluşturun",
    triggerOn: "Açık ",
    triggerMakePagesVisible: "Sayfayı görünür yap:",
    triggerMakeQuestionsVisible: "Ögeleri görünür yap:",
    triggerCompleteText: "Complete the survey if succeed.",
    triggerNotSet: "Tetikleyici ayarlanmadı",
    triggerRunIf: "Run if",
    triggerSetToName: "Değerini değiştir: ",
    triggerFromName: "Değeri şuradan kopyala: ",
    triggerRunExpression: "Bu ifadeyi çalıştır:",
    triggerSetValue: "to: ",
    triggerIsVariable: "Değişkeni anket sonucuna koymayın."
  },
  //Property values
  pv: {
    true: "doğru",
    false: "yanlış",
    inherit: "inherit",
    show: "göster",
    hide: "gizle",
    default: "varsayılan",
    initial: "ilk",
    random: "rastgele",
    collapsed: "collapsed",
    expanded: "genişletilmiş",
    none: "yok",
    asc: "yükselen",
    desc: "azalan",
    indeterminate: "belirsiz",
    decimal: "ondalık",
    currency: "currency",
    percent: "yüzde",
    firstExpanded: "firstExpanded",
    off: "kapalı",
    onPanel: "Panelde",
    onSurvey: "Ankette",
    list: "liste",
    progressTop: "progressTop",
    progressBottom: "progressBottom",
    progressTopBottom: "progressTopBottom",
    horizontal: "yatay",
    vertical: "dikey",
    top: "üst",
    bottom: "alt",
    topBottom: "üst ve alt",
    left: "sol",
    color: "renk",
    date: "tarih",
    datetime: "tarih saat",
    "datetime-local": "yerel - tarih saat",
    email: "e posta",
    month: "ay",
    number: "numara",
    password: "şifre",
    range: "range",
    tel: "tel",
    text: "metin",
    time: "zaman",
    url: "url",
    week: "hafta",
    hidden: "gizli",
    on: "üzerinde",
    onPage: "Sayfa üzerinde",
    edit: "düzenle",
    display: "görüntüle",
    onComplete: "tamamlandı",
    onHidden: "gizlen",
    all: "tümü",
    page: "sayfa",
    survey: "ankey",
    onNextPage: "Sonraki sayfada",
    onValueChanged: "değer değişikliği"
  },
  //Operators
  op: {
    empty: "boş",
    notempty: "boş değil",
    equal: "eşit",
    notequal: "eşit değil",
    contains: "içeren",
    notcontains: "içermeyen",
    greater: "büyük",
    less: "küçük",
    greaterorequal: "büyük veya eşit",
    lessorequal: "küçük veya eşit"
  },
  //Embed window
  ew: {
    angular: "Use Angular version",
    jquery: "Use jQuery version",
    knockout: "Use Knockout version",
    react: "Use React version",
    vue: "Use Vue version",
    bootstrap: "For bootstrap framework",
    standard: "No bootstrap",
    showOnPage: "Show survey on a page",
    showInWindow: "Show survey in a window",
    loadFromServer: "Load Survey JSON from server",
    titleScript: "Scripts and styles",
    titleHtml: "HTML",
    titleJavaScript: "JavaScript"
  },
  //Test Survey
  ts: {
    selectPage: "Test etmek için sayfayı seçin:",
    showInvisibleElements: "Görünmez öğeler göster"
  },
  validators: {
    answercountvalidator: "cevap sayısı",
    emailvalidator: "e-posta",
    expressionvalidator: "ifade",
    numericvalidator: "sayısal",
    regexvalidator: "regex",
    textvalidator: "metin"
  },
  triggers: {
    completetrigger: "anketi tamamla",
    setvaluetrigger: "değeri ayarla",
    copyvaluetrigger: "değeri kopyala",
    runexpressiontrigger: "ifadeyi çalıştır",
    visibletrigger: "görünürlüğü değiştir"
  },
  //Properties
  p: {
    name: "ad",
    title: {
      name: "başlık",
      title: "Leave it empty, if it is the same as 'Name'"
    },

    navigationButtonsVisibility: "gezinmeDüğmeleriGörünürlüğü",
    questionsOrder: "questionsOrder",
    maxTimeToFinish: "maksimumBitirmeSüresi",

    visible: "görünür",
    visibleIf: "görülebilir",
    questionTitleLocation: "soruBaşlığıKonumu",
    description: "açıklama",
    state: "belirtmek",
    isRequired: "gerekli",
    indent: "satırbaşı",
    requiredErrorText: "zorunluAlanHataMetni",
    startWithNewLine: "yeniSatırlaBaşla",
    innerIndent: "içGirinti",
    page: "sayfa",

    width: "genişlik",

    commentText: "yorumMetni",
    valueName: "değerAdı",
    enableIf: "etkinse",
    defaultValue: "varsayılanDeğer",
    correctAnswer: "doğruCevap",
    readOnly: "saltOkunur",
    validators: "doğrulayıcılar",
    titleLocation: "başlıkKonumu",

    hasComment: "yorumYaptı",
    hasOther: "başkaVar",
    choices: "seçimler",
    choicesOrder: "choicesOrder",
    choicesByUrl: "choicesByUrl",
    otherText: "otherText",
    otherErrorText: "otherErrorText",
    storeOthersAsComment: "storeOthersAsComment",

    label: "etiket",
    showTitle: "başlığıGöster",
    valueTrue: "değerDoğru",
    valueFalse: "değerYanlış",

    cols: "sütunlar",
    rows: "satırlar",
    placeHolder: "yerTutucu",

    optionsCaption: "seçeneklerBaşlık",

    expression: "ifade",
    format: "format",
    displayStyle: "ekranStili",
    currency: "paraBirimi",
    useGrouping: "gruplandırmayıKullan",

    showPreview: "önizlemeyiGöster",
    allowMultiple: "birdençokİzinver",
    imageHeight: "resimYüksekliği",
    imageWidth: "resimGenişliği",
    storeDataAsText: "verileriMetinOlarakSakla",
    maxSize: "maksimumBoyut",

    html: "html",

    columns: "sütunlar",
    cells: "hücreler",
    isAllRowRequired: "tümSatırlarZorunlu",

    horizontalScroll: "yatayKaydırma",
    cellType: "cellType",
    columnsLayout: "columnsLayout",
    columnColCount: "columnColCount",
    columnMinWidth: "columnMinWidth",

    rowCount: "rowCount",
    minRowCount: "minRowCount",
    maxRowCount: "maxRowCount",
    keyName: "keyName",
    keyDuplicationError: "keyDuplicationError",
    confirmDelete: "confirmDelete",
    confirmDeleteText: "confirmDeleteText",
    addRowLocation: "addRowLocation",
    addRowText: "addRowText",
    removeRowText: "removeRowText",

    items: "öge",
    itemSize: "öğeBoyutu",
    colCount: "sütunSayısı",

    templateTitle: "templateTitle",
    templateDescription: "templateDescription",
    allowAddPanel: "allowAddPanel",
    allowRemovePanel: "allowRemovePanel",
    panelCount: "panelCount",
    minPanelCount: "minPanelCount",
    maxPanelCount: "maxPanelCount",
    panelsState: "panelsState",
    panelAddText: "panelAddText",
    panelRemoveText: "panelRemoveText",
    panelPrevText: "panelPrevText",
    panelNextText: "panelNextText",
    showQuestionNumbers: "showQuestionNumbers",
    showRangeInProgress: "showRangeInProgress",
    renderMode: "renderMode",
    templateTitleLocation: "templateTitleLocation",

    rateValues: "oylamaDeğerleri",
    rateMin: "minimumOy",
    rateMax: "maksimumOy",
    rateStep: "oyAdımı",
    minRateDescription: "minimumOyAçıklaması",
    maxRateDescription: "maksimumOyAçıklaması",

    inputType: "girişTipi",
    size: "boyut",

    locale: "yerel",
    focusFirstQuestionAutomatic: "ilkSoruyaOtomatikOdaklan",
    completedHtml: "completedHtml",
    completedBeforeHtml: "completedBeforeHtml",
    loadingHtml: "loadingHtml",
    triggers: "tetikleyiciler",
    cookieName: "cookieAdı",
    sendResultOnPageNext: "sonucuSonrakiSayfayaGönder",
    showNavigationButtons: "gezinmeDüğmeleriniGöster",
    showPrevButton: "geriDönmeButonunuGöster",
    showPageTitles: "sayfaBaşlıklarınıGöster",
    showCompletedPage: "tamamlandıSayfasınıGöster",
    showPageNumbers: "sayfaNumaralarınıGöster",
    questionErrorLocation: "soruHataYeri",
    showProgressBar: "ilerlemeÇubuğunuGöster",
    mode: "modu",
    goNextPageAutomatic: "otamatikSonrakiSayfayaGeç",
    checkErrorsMode: "hatalarıKontrolEtmeModu",
    clearInvisibleValues: "görünmeyenDeğerleriTemizle",
    startSurveyText: "anketMetniniBaşlat",
    pagePrevText: "öncekiSayfaMetni",
    pageNextText: "sonrakiSayfaMetni",
    completeText: "completeText",
    requiredText: "zorunluAlanMetni",
    questionStartIndex: "soruBaşlangıçDizini",
    questionTitleTemplate: "soruBaşlığıŞablonu",
    firstPageIsStarted: "firstPageIsStarted",
    isSinglePage: "tekSayfa",
    maxTimeToFinishPage: "maxTimeToFinishPage",
    showTimerPanel: "showTimerPanel",
    showTimerPanelMode: "showTimerPanelMode",

    defaultPanelValue: "defaultPanelValue",
    defaultRowValue: "defaultRowValue",
    hasNone: "hasNone",
    noneText: "noneText",

    text: "metin",
    minValue: "minimum değer",
    maxValue: "maksimum değer",
    minLength: "minimum uzunluk",
    maxLength: "maksimum uzunluk",
    allowDigits: "rakamlara izin ver",
    minCount: "minimum sayım",
    maxCount: "maksimum sayım",
    regex: "düzenli ifade"
  }
};
//Uncomment this line on creating a translation file. You should replace "en" and enStrings with your locale ("fr", "de" and so on) and your variable.
editorLocalization.locales["tr"] = turkishStrings;
